-- ============================================================================
-- Supabase Migration Engine Rebuild Script
-- ============================================================================
-- This script completely rebuilds the migration engine tables.
-- Run this ONCE in the Supabase SQL Editor to normalize the migration system.
-- ============================================================================

BEGIN;

-- Drop old schema_migrations table if it exists
DROP TABLE IF EXISTS supabase_migrations.schema_migrations CASCADE;

-- Ensure schema exists
CREATE SCHEMA IF NOT EXISTS supabase_migrations;

-- Create migrations table with correct schema
CREATE TABLE IF NOT EXISTS supabase_migrations.migrations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version text NOT NULL,
    name text NOT NULL,
    hash text NOT NULL,
    executed_at timestamptz NOT NULL DEFAULT now(),
    statements text NOT NULL
);

-- Truncate existing data
TRUNCATE TABLE supabase_migrations.migrations;

-- Insert all migrations
INSERT INTO supabase_migrations.migrations (version, name, hash, executed_at, statements)
VALUES ('20241117', 'add_core_tables', '2464f76dcbabba10b975aa149b86fa574174f6f4ed1600517b3d264b0ff199ac', now(), '-- Vella core schema migration

create extension if not exists "pgcrypto";

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  avatar_url text,
  timezone text default ''UTC'',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

do $$
begin
  if not exists (select 1 from pg_type where typname = ''subscription_plan'') then
    create type subscription_plan as enum (''free'', ''pro'', ''elite'');
  end if;
end $$;

create table if not exists public.subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  plan subscription_plan not null default ''free'',
  stripe_customer_id text,
  stripe_subscription_id text,
  status text not null default ''inactive'',
  monthly_token_allocation bigint not null default 0,
  token_balance bigint not null default 0,
  current_period_start timestamptz,
  current_period_end timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists subscriptions_user_id_idx on public.subscriptions(user_id);

create unique index if not exists subscriptions_user_unique on public.subscriptions(user_id);

create table if not exists public.token_topups (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  stripe_payment_intent_id text,
  stripe_charge_id text,
  pack_name text not null,
  tokens_awarded bigint not null,
  amount_usd numeric(10, 2) not null,
  status text not null,
  created_at timestamptz default now()
);

create index if not exists token_topups_user_id_idx on public.token_topups(user_id);

create table if not exists public.token_usage (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  source text not null,
  tokens bigint not null,
  from_allocation boolean not null,
  created_at timestamptz default now()
);

create index if not exists token_usage_user_id_idx on public.token_usage(user_id);

create index if not exists token_usage_created_at_idx on public.token_usage(created_at);

-- emotion_logs and journal_entries removed - now stored locally only

create table if not exists public.conversation_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  started_at timestamptz default now(),
  ended_at timestamptz,
  mode text not null,
  created_at timestamptz default now()
);

create index if not exists conversation_sessions_user_id_idx on public.conversation_sessions(user_id);

do $$
begin
  if exists (select 1 from pg_class c join pg_namespace n on n.oid = c.relnamespace where n.nspname = ''public'' and c.relname = ''profiles'' and not c.relrowsecurity) then
    alter table public.profiles enable row level security;
  end if;
end $$;

do $$
begin
  if exists (select 1 from pg_class c join pg_namespace n on n.oid = c.relnamespace where n.nspname = ''public'' and c.relname = ''subscriptions'' and not c.relrowsecurity) then
    alter table public.subscriptions enable row level security;
  end if;
end $$;

do $$
begin
  if exists (select 1 from pg_class c join pg_namespace n on n.oid = c.relnamespace where n.nspname = ''public'' and c.relname = ''token_topups'' and not c.relrowsecurity) then
    alter table public.token_topups enable row level security;
  end if;
end $$;

do $$
begin
  if exists (select 1 from pg_class c join pg_namespace n on n.oid = c.relnamespace where n.nspname = ''public'' and c.relname = ''token_usage'' and not c.relrowsecurity) then
    alter table public.token_usage enable row level security;
  end if;
end $$;

do $$
begin
  if exists (select 1 from pg_class c join pg_namespace n on n.oid = c.relnamespace where n.nspname = ''public'' and c.relname = ''conversation_sessions'' and not c.relrowsecurity) then
    alter table public.conversation_sessions enable row level security;
  end if;
end $$;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = ''public'' and tablename = ''profiles'' and policyname = ''users_select_own_profiles'') then
    create policy "users_select_own_profiles" on public.profiles
    for select using (auth.uid() = id);
  end if;
end $$;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = ''public'' and tablename = ''profiles'' and policyname = ''users_insert_own_profile'') then
    create policy "users_insert_own_profile" on public.profiles
    for insert with check (auth.uid() = id);
  end if;
end $$;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = ''public'' and tablename = ''profiles'' and policyname = ''users_update_own_profile'') then
    create policy "users_update_own_profile" on public.profiles
    for update using (auth.uid() = id);
  end if;
end $$;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = ''public'' and tablename = ''profiles'' and policyname = ''users_delete_own_profile'') then
    create policy "users_delete_own_profile" on public.profiles
    for delete using (auth.uid() = id);
  end if;
end $$;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = ''public'' and tablename = ''subscriptions'' and policyname = ''users_select_own_subscriptions'') then
    create policy "users_select_own_subscriptions" on public.subscriptions
    for select using (auth.uid() = user_id);
  end if;
end $$;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = ''public'' and tablename = ''subscriptions'' and policyname = ''users_insert_own_subscriptions'') then
    create policy "users_insert_own_subscriptions" on public.subscriptions
    for insert with check (auth.uid() = user_id);
  end if;
end $$;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = ''public'' and tablename = ''subscriptions'' and policyname = ''users_update_own_subscriptions'') then
    create policy "users_update_own_subscriptions" on public.subscriptions
    for update using (auth.uid() = user_id);
  end if;
end $$;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = ''public'' and tablename = ''subscriptions'' and policyname = ''users_delete_own_subscriptions'') then
    create policy "users_delete_own_subscriptions" on public.subscriptions
    for delete using (auth.uid() = user_id);
  end if;
end $$;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = ''public'' and tablename = ''token_topups'' and policyname = ''users_select_own_topups'') then
    create policy "users_select_own_topups" on public.token_topups
    for select using (auth.uid() = user_id);
  end if;
end $$;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = ''public'' and tablename = ''token_topups'' and policyname = ''users_insert_own_topups'') then
    create policy "users_insert_own_topups" on public.token_topups
    for insert with check (auth.uid() = user_id);
  end if;
end $$;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = ''public'' and tablename = ''token_usage'' and policyname = ''users_select_own_usage'') then
    create policy "users_select_own_usage" on public.token_usage
    for select using (auth.uid() = user_id);
  end if;
end $$;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = ''public'' and tablename = ''token_usage'' and policyname = ''users_insert_own_usage'') then
    create policy "users_insert_own_usage" on public.token_usage
    for insert with check (auth.uid() = user_id);
  end if;
end $$;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = ''public'' and tablename = ''conversation_sessions'' and policyname = ''users_select_own_conversation_sessions'') then
    create policy "users_select_own_conversation_sessions" on public.conversation_sessions
    for select using (auth.uid() = user_id);
  end if;
end $$;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = ''public'' and tablename = ''conversation_sessions'' and policyname = ''users_insert_own_conversation_sessions'') then
    create policy "users_insert_own_conversation_sessions" on public.conversation_sessions
    for insert with check (auth.uid() = user_id);
  end if;
end $$;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = ''public'' and tablename = ''conversation_sessions'' and policyname = ''users_update_own_conversation_sessions'') then
    create policy "users_update_own_conversation_sessions" on public.conversation_sessions
    for update using (auth.uid() = user_id);
  end if;
end $$;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = ''public'' and tablename = ''conversation_sessions'' and policyname = ''users_delete_own_conversation_sessions'') then
    create policy "users_delete_own_conversation_sessions" on public.conversation_sessions
    for delete using (auth.uid() = user_id);
  end if;
end $$;
');

INSERT INTO supabase_migrations.migrations (version, name, hash, executed_at, statements)
VALUES ('20250101', 'drop_sensitive_tables', 'b333f20dcdf9544e21bf4179ae6975b722ec18b381506549cdec54b0831daf89', now(), '-- placeholder (already applied remotely)
-- this file exists only to satisfy Supabase CLI matching rules
');

INSERT INTO supabase_migrations.migrations (version, name, hash, executed_at, statements)
VALUES ('20250101000000', 'vella_core_admin', 'fe8289446c678cb298ff3c027a48e3636794c0d2b2c890c34adc58436ffe324a', now(), '-- ============================================================================
-- Vella Core Admin Schema Migration
-- ============================================================================
-- This migration creates all tables required for:
-- 1. MOBILE Vella app runtime (admin config, policy, logging)
-- 2. vella-control admin panel (user management, logs, feedback, analytics)
--
-- IMPORTANT: These tables store ONLY SAFE METADATA:
-- - No conversational text, no journal text, no emotional notes
-- - No AI free-text responses, no raw prompts
-- - Only: user IDs, plan tiers, token balances, counters, timestamps, flags,
--   numeric ratings, categories, short codes
-- ============================================================================

begin;

-- ============================================================================
-- 1. ADMIN CONFIGURATION TABLES
-- ============================================================================

-- admin_ai_config: Active AI configuration consumed by MOBILE runtime
-- MOBILE reads: MOBILE/lib/admin/adminConfig.ts -> loadActiveAdminAIConfig()
create table if not exists public.admin_ai_config (
  id uuid primary key default gen_random_uuid(),
  config jsonb not null default ''{}''::jsonb,
  is_active boolean not null default false,
  label text, -- optional version label, no user text
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists admin_ai_config_is_active_idx on public.admin_ai_config(is_active) where is_active = true;

comment on table public.admin_ai_config is ''Active AI configuration consumed by MOBILE runtime. Stores AdminAIConfig JSON structure. Only metadata, no user text.'';
comment on column public.admin_ai_config.config is ''AdminAIConfig JSON structure with persona, behaviour, voice, model, memory, safety, automation settings'';
comment on column public.admin_ai_config.is_active is ''Only one row should be active at a time. MOBILE runtime queries WHERE is_active = true'';

-- admin_global_config: Admin panel''s global configuration storage
-- Admin panel reads/writes: apps/vella-control/app/api/admin/config/*
-- Note: This table already exists but needs the ''active'' column
alter table if exists public.admin_global_config
  add column if not exists active boolean not null default false;

do $$
begin
  if exists (
    select 1 from pg_tables
    where schemaname = ''public''
    and tablename = ''admin_global_config''
  ) then

    -- admin_global_config comments
    comment on table public.admin_global_config is ''Admin panel global configuration storage. Same config as admin_ai_config but source of truth for admin UI.'';
    comment on column public.admin_global_config.active is ''Only one row should be active at a time. Admin panel queries WHERE active = true'';

    -- enable RLS
    alter table public.admin_global_config enable row level security;

    -- admin-only policy
    drop policy if exists "admin_only_admin_global_config" on public.admin_global_config;
    create policy "admin_only_admin_global_config" on public.admin_global_config
      for all
      using (
        auth.jwt() ->> ''role'' = ''service_role'' or public.is_admin_user()
      );

  end if;
end;
$$;

-- ============================================================================
-- 2. USER METADATA TABLE (Admin-Managed User Policy)
-- ============================================================================

-- user_metadata: Admin-managed user metadata for policy control
-- MOBILE reads: MOBILE/lib/admin/adminPolicy.ts -> loadAdminUserPolicy()
-- Admin panel reads/writes: apps/vella-control/app/api/admin/users/*
create table if not exists public.user_metadata (
  user_id uuid primary key references auth.users(id) on delete cascade,
  plan text, -- plan name string (e.g., ''free'', ''pro'', ''elite'')
  token_balance bigint, -- admin override token balance
  status text, -- ''active'', ''disabled'', ''blocked''
  voice_enabled boolean,
  realtime_beta boolean,
  tokens_per_month bigint, -- monthly token limit
  notes text, -- admin-side notes only (no user text, max 500 chars)
  email text, -- from auth.users, denormalized for admin panel
  full_name text, -- from auth.users, denormalized for admin panel
  last_active_at timestamptz,
  admin boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists user_metadata_status_idx on public.user_metadata(status);
create index if not exists user_metadata_last_active_at_idx on public.user_metadata(last_active_at);

comment on table public.user_metadata is ''Admin-managed user metadata for policy control. No user free-text content.'';
comment on column public.user_metadata.notes is ''Admin-side notes only, max 500 chars. No user conversational text.'';
comment on column public.user_metadata.status is ''User status: active, disabled, or blocked. Controls canStartSession in MOBILE runtime.'';

-- ============================================================================
-- 3. ADMIN LOGGING TABLES
-- ============================================================================

-- system_logs: Runtime system logs from MOBILE app
-- MOBILE writes: MOBILE/lib/admin/runtimeEvents.ts -> recordAdminRuntimeLog()
-- Admin panel reads: apps/vella-control/app/api/admin/logs/list
create table if not exists public.system_logs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references public.profiles(id) on delete set null,
  level text not null check (level in (''info'', ''warn'', ''error'')),
  source text not null, -- short code like ''tokens'', ''safety'', ''realtime''
  code text, -- machine code like ''DISTRESS_HIGH'', ''INSUFFICIENT_TOKENS''
  message text not null, -- SHORT label only (max 200 chars, no user text, no AI text)
  metadata jsonb, -- numeric flags, scores, but never raw text
  created_at timestamptz not null default now()
);

create index if not exists system_logs_created_at_idx on public.system_logs(created_at desc);
create index if not exists system_logs_level_idx on public.system_logs(level);
create index if not exists system_logs_user_id_idx on public.system_logs(user_id);
create index if not exists system_logs_source_idx on public.system_logs(source);

comment on table public.system_logs is ''Runtime system logs from MOBILE app. No user free-text content, only metadata and short labels.'';
comment on column public.system_logs.message is ''Short label only (max 200 chars). No user conversational text, no AI responses.'';
comment on column public.system_logs.metadata is ''Numeric flags, scores, timestamps. Never raw text content.'';

-- admin_activity_log: Admin panel action audit trail
-- Admin panel writes: All admin mutation routes log here
-- Admin panel reads: apps/vella-control/app/api/admin/logs/list
create table if not exists public.admin_activity_log (
  id uuid primary key default gen_random_uuid(),
  admin_id uuid not null references auth.users(id) on delete set null, -- admin user who performed action
  action text not null, -- short code like ''config.save'', ''users.update-plan''
  previous jsonb, -- previous state snapshot
  next jsonb, -- new state snapshot
  created_at timestamptz not null default now()
);

create index if not exists admin_activity_log_created_at_idx on public.admin_activity_log(created_at desc);
create index if not exists admin_activity_log_admin_id_idx on public.admin_activity_log(admin_id);
create index if not exists admin_activity_log_action_idx on public.admin_activity_log(action);

comment on table public.admin_activity_log is ''Admin panel action audit trail. Tracks all admin mutations for audit purposes.'';

-- ============================================================================
-- 4. FEEDBACK & REPORTS TABLES
-- ============================================================================

-- feedback: User feedback summaries (numeric ratings, categories, no free-text)
-- MOBILE writes: MOBILE/lib/admin/runtimeEvents.ts -> recordAdminFeedbackSummary()
-- Admin panel reads: apps/vella-control/app/feedback/page.tsx
create table if not exists public.feedback (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  session_id uuid, -- optional session reference
  rating integer check (rating >= 1 and rating <= 10), -- 1-10 scale
  channel text not null check (channel in (''voice'', ''text'')),
  category text, -- finite set: ''clarity'', ''warmth'', ''helpfulness'', etc.
  created_at timestamptz not null default now()
);

create index if not exists feedback_user_id_idx on public.feedback(user_id);
create index if not exists feedback_created_at_idx on public.feedback(created_at);
create index if not exists feedback_channel_idx on public.feedback(channel);
create index if not exists feedback_rating_idx on public.feedback(rating);

comment on table public.feedback is ''User feedback summaries. Only numeric ratings and categories, no free-text comments.'';
comment on column public.feedback.rating is ''Numeric rating 1-10. No qualitative text feedback stored.'';
comment on column public.feedback.category is ''Finite category set. No open-ended user comments.'';

-- ============================================================================
-- 5. TOKEN LEDGER (Admin Token Adjustments)
-- ============================================================================

-- token_ledger: Audit trail for token balance changes
-- Admin panel writes: apps/vella-control/app/api/admin/users/update-tokens
create table if not exists public.token_ledger (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  delta bigint not null, -- positive for additions, negative for deductions
  reason text not null, -- short code like ''admin_adjustment'', ''purchase'', ''refund''
  created_at timestamptz not null default now()
);

create index if not exists token_ledger_user_id_idx on public.token_ledger(user_id);
create index if not exists token_ledger_created_at_idx on public.token_ledger(created_at);

comment on table public.token_ledger is ''Audit trail for token balance changes. Tracks admin adjustments and purchases.'';

-- ============================================================================
-- 6. ANALYTICS TABLES
-- ============================================================================

-- analytics_counters: Pre-computed analytics counters for admin dashboard
-- Admin panel reads: apps/vella-control/app/api/admin/analytics/get
create table if not exists public.analytics_counters (
  key text primary key, -- counter name like ''total_users'', ''active_users_7d'', ''total_tokens_used''
  value bigint not null default 0,
  updated_at timestamptz not null default now()
);

comment on table public.analytics_counters is ''Pre-computed analytics counters for admin dashboard. Simple key-value store.'';

-- ============================================================================
-- 7. ROW LEVEL SECURITY (RLS) POLICIES
-- ============================================================================

-- Enable RLS on all new admin tables
alter table public.admin_ai_config enable row level security;
alter table public.user_metadata enable row level security;
alter table public.system_logs enable row level security;
alter table public.admin_activity_log enable row level security;
alter table public.feedback enable row level security;
alter table public.token_ledger enable row level security;
alter table public.analytics_counters enable row level security;

-- Admin-only policies: Only service-role or admin users can access
-- These policies use a helper function to check if the user is an admin

-- Helper function to check if user is admin (via user_metadata.admin flag)
create or replace function public.is_admin_user()
returns boolean as $$
begin
  -- Service role bypasses RLS, so this function is for authenticated users
  -- Check if user exists in user_metadata with admin = true
  return exists (
    select 1
    from public.user_metadata
    where user_id = auth.uid()
    and admin = true
  );
end;
$$ language plpgsql security definer;

-- admin_ai_config: MOBILE can read active config, admin can write
drop policy if exists "admin_ai_config_read" on public.admin_ai_config;
create policy "admin_ai_config_read" on public.admin_ai_config
  for select
  using (true); -- All authenticated users can read active config (MOBILE runtime needs this)

drop policy if exists "admin_ai_config_write" on public.admin_ai_config;
create policy "admin_ai_config_write" on public.admin_ai_config
  for all
  using (
    auth.jwt() ->> ''role'' = ''service_role'' or public.is_admin_user()
  )
  with check (
    auth.jwt() ->> ''role'' = ''service_role'' or public.is_admin_user()
  );

-- user_metadata: MOBILE can read own policy, admin can read/write all
drop policy if exists "user_metadata_read_own" on public.user_metadata;
create policy "user_metadata_read_own" on public.user_metadata
  for select
  using (
    auth.uid() = user_id or -- Users can read their own metadata (MOBILE runtime needs this)
    auth.jwt() ->> ''role'' = ''service_role'' or public.is_admin_user()
  );

drop policy if exists "user_metadata_write" on public.user_metadata;
create policy "user_metadata_write" on public.user_metadata
  for all
  using (
    auth.jwt() ->> ''role'' = ''service_role'' or public.is_admin_user()
  )
  with check (
    auth.jwt() ->> ''role'' = ''service_role'' or public.is_admin_user()
  );

-- system_logs: MOBILE can write (insert), admin can read
drop policy if exists "system_logs_insert" on public.system_logs;
create policy "system_logs_insert" on public.system_logs
  for insert
  with check (
    auth.uid() = user_id or user_id is null -- Users can insert logs for themselves or system logs
  );

drop policy if exists "system_logs_read" on public.system_logs;
create policy "system_logs_read" on public.system_logs
  for select
  using (
    auth.jwt() ->> ''role'' = ''service_role'' or public.is_admin_user()
  );

-- admin_activity_log: Admin-only access
drop policy if exists "admin_only_admin_activity_log" on public.admin_activity_log;
create policy "admin_only_admin_activity_log" on public.admin_activity_log
  for all
  using (
    auth.jwt() ->> ''role'' = ''service_role'' or public.is_admin_user()
  );

-- feedback: MOBILE can write (insert), admin can read
drop policy if exists "feedback_insert" on public.feedback;
create policy "feedback_insert" on public.feedback
  for insert
  with check (
    auth.uid() = user_id -- Users can insert feedback for themselves
  );

drop policy if exists "feedback_read" on public.feedback;
create policy "feedback_read" on public.feedback
  for select
  using (
    auth.jwt() ->> ''role'' = ''service_role'' or public.is_admin_user()
  );

-- token_ledger: Admin-only access
drop policy if exists "admin_only_token_ledger" on public.token_ledger;
create policy "admin_only_token_ledger" on public.token_ledger
  for all
  using (
    auth.jwt() ->> ''role'' = ''service_role'' or public.is_admin_user()
  );

-- analytics_counters: Admin-only access
drop policy if exists "admin_only_analytics_counters" on public.analytics_counters;
create policy "admin_only_analytics_counters" on public.analytics_counters
  for all
  using (
    auth.jwt() ->> ''role'' = ''service_role'' or public.is_admin_user()
  );

-- ============================================================================
-- 8. ANALYTICS VIEWS (Optional, for Admin Dashboard)
-- ============================================================================

-- admin_feedback_summary_view: Aggregated feedback statistics
create or replace view public.admin_feedback_summary_view as
with base as (
  select *
  from public.feedback
),
agg as (
  select
    count(*) as total_feedback,
    avg(rating) as avg_rating,
    max(created_at) as last_updated
  from base
),
channel_stats as (
  select
    channel,
    count(*) as cnt,
    avg(rating) as avg_rating
  from base
  where channel is not null
  group by channel
),
category_stats as (
  select
    category,
    count(*) as cnt,
    avg(rating) as avg_rating
  from base
  where category is not null
  group by category
)
select
  agg.total_feedback,
  agg.avg_rating,
  (
    select jsonb_object_agg(
      channel,
      jsonb_build_object(
        ''count'', cnt,
        ''avg_rating'', avg_rating
      )
    )
    from channel_stats
  ) as rating_by_channel,
  (
    select jsonb_object_agg(
      category,
      jsonb_build_object(
        ''count'', cnt,
        ''avg_rating'', avg_rating
      )
    )
    from category_stats
  ) as rating_by_category,
  agg.last_updated
from agg;

comment on view public.admin_feedback_summary_view is ''Aggregated feedback statistics for admin dashboard. Admin-only access via RLS.'';

-- Grant access to view (RLS on underlying table applies)
grant select on public.admin_feedback_summary_view to authenticated;

-- ============================================================================
-- COMMENTS & DOCUMENTATION
-- ============================================================================

comment on schema public is ''Vella core schema. All tables store ONLY safe metadata - no conversational text, no journal text, no emotional notes. Personal content stays in browser local storage.'';

commit;

');

INSERT INTO supabase_migrations.migrations (version, name, hash, executed_at, statements)
VALUES ('20250217', 'token_engine', '0fef2693aea12f8dbefd26b37499fa40ec554e570cd1a6f6d1fed3d1b99ec443', now(), 'begin;

create table if not exists public.token_rates (
  event text primary key,
  cost int not null
);

insert into public.token_rates (event, cost) values
  (''text_short'', 300),
  (''text_long'', 500),
  (''emotion_reflection'', 700),
  (''deep_dive'', 1200),
  (''story_short'', 1500),
  (''story_long'', 3000),
  (''story_guided'', 2500),
  (''voice_minute'', 1200),
  (''voice_quick_question'', 300),
  (''voice_interval'', 600),
  (''checkin'', 200),
  (''journal_prompt'', 200),
  (''daily_insight'', 400)
on conflict (event) do nothing;

alter table public.subscriptions
  add column if not exists monthly_token_allocation_used bigint not null default 0;

alter table public.profiles
  add column if not exists app_language text default ''en'',
  add column if not exists theme text default ''system'';

create table if not exists public.user_preferences (
  user_id uuid primary key references auth.users(id) on delete cascade,
  notifications_enabled boolean not null default true,
  daily_checkin boolean not null default false,
  journaling_prompts boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.vella_settings (
  user_id uuid primary key references auth.users(id) on delete cascade,
  voice_model text not null default ''luna'',
  tone text not null default ''soft'',
  tone_style text not null default ''soft'',
  relationship_mode text not null default ''best_friend'',
  voice_hud jsonb not null default
    ''{"moodChip":true,"stability":true,"deliveryHints":true,"sessionTime":true,"tokenChip":true,"strategyChip":true,"alertChip":true}''::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function reset_monthly_tokens()
returns void as $$
begin
  update public.subscriptions
  set monthly_token_allocation_used = 0
  where status = ''active'';
end;
$$ language plpgsql;

commit;

');

INSERT INTO supabase_migrations.migrations (version, name, hash, executed_at, statements)
VALUES ('20250218', 'add_adaptive_traits', '6881f1ef7c487562856c8b25c9af4998f56cdab52be9fbf88173bc740fb5688a', now(), 'create table if not exists public.user_traits (
  user_id uuid primary key references auth.users (id) on delete cascade,
  resilience numeric not null default 50,
  clarity numeric not null default 50,
  discipline numeric not null default 50,
  emotional_stability numeric not null default 50,
  motivation numeric not null default 50,
  self_compassion numeric not null default 50,
  last_computed_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.user_traits_history (
  id bigserial primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  window_start timestamptz not null,
  window_end timestamptz not null,
  resilience numeric not null,
  clarity numeric not null,
  discipline numeric not null,
  emotional_stability numeric not null,
  motivation numeric not null,
  self_compassion numeric not null,
  source text not null default ''auto'',
  created_at timestamptz not null default now()
);

create index if not exists user_traits_history_user_window_idx
  on public.user_traits_history (user_id, window_start desc);

do $$
begin
  if exists (select 1 from pg_class c join pg_namespace n on n.oid = c.relnamespace where n.nspname = ''public'' and c.relname = ''user_traits'' and not c.relrowsecurity) then
    alter table public.user_traits enable row level security;
  end if;
end $$;

do $$
begin
  if exists (select 1 from pg_class c join pg_namespace n on n.oid = c.relnamespace where n.nspname = ''public'' and c.relname = ''user_traits_history'' and not c.relrowsecurity) then
    alter table public.user_traits_history enable row level security;
  end if;
end $$;

do $policy$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = ''public''
      and tablename = ''user_traits''
      and policyname = ''Allow users to read their trait state''
  ) then
    create policy "Allow users to read their trait state"
      on public.user_traits
      for select
      using (auth.uid() = user_id);
  end if;
end;
$policy$;

do $policy$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = ''public''
      and tablename = ''user_traits_history''
      and policyname = ''Allow users to read their trait history''
  ) then
    create policy "Allow users to read their trait history"
      on public.user_traits_history
      for select
      using (auth.uid() = user_id);
  end if;
end;
$policy$;
');

INSERT INTO supabase_migrations.migrations (version, name, hash, executed_at, statements)
VALUES ('20250219', 'add_nudge_history', 'baa7096617d09e78ccc8153fcdab7a0fec8b816c2e85a0d0611fdf5f3c5e5e90', now(), 'create table if not exists public.user_nudges (
  id bigserial primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  nudge_type text not null,
  message text not null,
  created_at timestamptz not null default now()
);

create index if not exists user_nudges_user_created_idx
  on public.user_nudges (user_id, created_at desc);

alter table public.user_nudges enable row level security;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = ''public''
      AND tablename = ''user_nudges''
      AND policyname = ''Users select their nudges''
  ) THEN
    CREATE POLICY "Users select their nudges"
      ON public.user_nudges
      FOR SELECT
      USING (auth.uid() = user_id);
  END IF;
END $$;

create policy "Users insert their nudges"
  on public.user_nudges
  for insert
  with check (auth.uid() = user_id);

');

INSERT INTO supabase_migrations.migrations (version, name, hash, executed_at, statements)
VALUES ('20250220', 'add_feature_tables', '2fe007676578e19a3048702429d79f0ca3d23f4e6811f644dd5e4d257dc5db29', now(), '-- Consolidated migration: feature tables (micro_rag_cache, progress_metrics, social_models, vella_personality)

create table if not exists public.micro_rag_cache (
  user_id uuid primary key references auth.users(id) on delete cascade,
  data jsonb not null,
  updated_at timestamptz not null default now()
);

create index if not exists micro_rag_cache_updated_at_idx on public.micro_rag_cache(updated_at);

create table if not exists public.progress_metrics (
  user_id uuid primary key references auth.users(id) on delete cascade,
  data jsonb not null,
  updated_at timestamptz not null default now()
);

do $$
begin
  if not exists (
    select 1 from information_schema.columns
    where table_name = ''progress_metrics'' and column_name = ''consistency_score''
  ) then
    alter table public.progress_metrics
      add column consistency_score double precision not null default 0;
  end if;

  if not exists (
    select 1 from information_schema.columns
    where table_name = ''progress_metrics'' and column_name = ''emotional_openness''
  ) then
    alter table public.progress_metrics
      add column emotional_openness double precision not null default 0;
  end if;

  if not exists (
    select 1 from information_schema.columns
    where table_name = ''progress_metrics'' and column_name = ''improvement_score''
  ) then
    alter table public.progress_metrics
      add column improvement_score double precision not null default 0;
  end if;

  if not exists (
    select 1 from information_schema.columns
    where table_name = ''progress_metrics'' and column_name = ''stability_score''
  ) then
    alter table public.progress_metrics
      add column stability_score double precision not null default 0;
  end if;

  if not exists (
    select 1 from information_schema.columns
    where table_name = ''progress_metrics'' and column_name = ''connection_index''
  ) then
    alter table public.progress_metrics
      add column connection_index double precision not null default 0;
  end if;
end
$$;

create table if not exists public.social_models (
  user_id uuid primary key references auth.users(id) on delete cascade,
  model jsonb not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.vella_personality (
  user_id uuid primary key references auth.users(id) on delete cascade,
  traits jsonb not null,
  updated_at timestamptz not null default now()
);

');

INSERT INTO supabase_migrations.migrations (version, name, hash, executed_at, statements)
VALUES ('20250221', 'add_progress_features', '575421ec17cc6d3d72abd59ec942749fc4cacf327964e2c2a1cc9207a93fc5ba', now(), '-- Consolidated migration: progress features (connection_depth, last_active, progress_metrics schema)

create table if not exists public.connection_depth (
  user_id uuid primary key references auth.users(id) on delete cascade,
  depth_score double precision not null default 0,
  last_increase timestamptz default now(),
  last_reciprocated timestamptz,
  updated_at timestamptz default now()
);

alter table public.profiles
  add column if not exists last_active timestamptz;

create table if not exists public.progress_metrics (
  user_id uuid primary key references auth.users(id) on delete cascade,
  consistency_score double precision not null default 0,
  emotional_openness double precision not null default 0,
  improvement_score double precision not null default 0,
  stability_score double precision not null default 0,
  connection_index double precision not null default 0,
  data jsonb,
  updated_at timestamptz default now()
);

do $$
begin
  if not exists (
    select 1 from information_schema.columns
    where table_name = ''progress_metrics'' and column_name = ''consistency_score''
  ) then
    alter table public.progress_metrics add column consistency_score double precision not null default 0;
  end if;

  if not exists (
    select 1 from information_schema.columns
    where table_name = ''progress_metrics'' and column_name = ''emotional_openness''
  ) then
    alter table public.progress_metrics add column emotional_openness double precision not null default 0;
  end if;

  if not exists (
    select 1 from information_schema.columns
    where table_name = ''progress_metrics'' and column_name = ''improvement_score''
  ) then
    alter table public.progress_metrics add column improvement_score double precision not null default 0;
  end if;

  if not exists (
    select 1 from information_schema.columns
    where table_name = ''progress_metrics'' and column_name = ''stability_score''
  ) then
    alter table public.progress_metrics add column stability_score double precision not null default 0;
  end if;

  if not exists (
    select 1 from information_schema.columns
    where table_name = ''progress_metrics'' and column_name = ''connection_index''
  ) then
    alter table public.progress_metrics add column connection_index double precision not null default 0;
  end if;

  if not exists (
    select 1 from information_schema.columns
    where table_name = ''progress_metrics'' and column_name = ''data''
  ) then
    alter table public.progress_metrics add column data jsonb;
  end if;
end
$$;

');

INSERT INTO supabase_migrations.migrations (version, name, hash, executed_at, statements)
VALUES ('20250222', 'add_last_active_at', '8474f928a233b73bbb8a45a5379f802cd307c179355aabbf0c61b1da8546e7a6', now(), 'alter table public.profiles
  add column if not exists last_active_at timestamptz;

');

INSERT INTO supabase_migrations.migrations (version, name, hash, executed_at, statements)
VALUES ('20250223', 'remove_checkin_note', '8233e5ec1a9371d400bfaf961861402b8827e23a3349c66e4498014abf16c5bf', now(), 'DO $$

BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = ''public''
        AND table_name = ''checkins''
    ) THEN
        ALTER TABLE public.checkins DROP COLUMN IF EXISTS note;
    END IF;
END $$;
');

INSERT INTO supabase_migrations.migrations (version, name, hash, executed_at, statements)
VALUES ('20251129154622', 'create_admin_global_config', '7e5088c5f4b82c8023cb788c5fc42fc4a0bbde576581c0410b868f5a3b84c318', now(), 'create table if not exists admin_global_config (
  id uuid primary key default gen_random_uuid(),
  config jsonb not null default ''{}''::jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

');

INSERT INTO supabase_migrations.migrations (version, name, hash, executed_at, statements)
VALUES ('20251219', 'drop_legacy_vella_settings_fields', '6aebb3cff8deec3b81be5f8ff74150ad7783fd0dbb1826bf502cb10b9a529265', now(), '-- Drop legacy Vella settings columns that are no longer used
ALTER TABLE vella_settings
  DROP COLUMN IF EXISTS cadence,
  DROP COLUMN IF EXISTS variability,
  DROP COLUMN IF EXISTS sarcasm_softness;

');

INSERT INTO supabase_migrations.migrations (version, name, hash, executed_at, statements)
VALUES ('20251220', 'fix_vella_settings', '062ee309a94cf726808a3605d34513f7b3f32e93a1a54b69ce21802409d2f8e5', now(), '-- Consolidated migration: vella_settings language and schema fixes

begin;

alter table public.vella_settings
  add column if not exists language text;

update public.vella_settings vs
set language = p.app_language
from public.profiles p
where vs.user_id = p.id
  and vs.language is null
  and p.app_language is not null;

update public.vella_settings
set language = ''en''
where language is null;

alter table public.vella_settings
  add column if not exists relationship_mode text default ''companion'',
  add column if not exists voice_hud jsonb default ''{}''::jsonb;

alter table public.vella_settings
  drop column if exists story_mode,
  drop column if exists cadence,
  drop column if exists variability,
  drop column if exists sarcasm_softness,
  drop column if exists conversation_language;

commit;

');

COMMIT;

-- ============================================================================
-- Validation Query (run after commit to verify)
-- ============================================================================
-- SELECT version, name, hash, executed_at 
-- FROM supabase_migrations.migrations 
-- ORDER BY version;
