#!/usr/bin/env python3
import hashlib
import os
import json
from pathlib import Path

migrations_dir = Path(__file__).parent.parent.parent / 'supabase' / 'migrations'
output_file = Path(__file__).parent.parent.parent / 'supabase' / 'rebuild_migration_engine.sql'

expected_migrations = [
    '20241117_add_core_tables.sql',
    '20250101_drop_sensitive_tables.sql',
    '20250101000000_vella_core_admin.sql',
    '20250217_token_engine.sql',
    '20250218_add_adaptive_traits.sql',
    '20250219_add_nudge_history.sql',
    '20250220_add_feature_tables.sql',
    '20250221_add_progress_features.sql',
    '20250222_add_last_active_at.sql',
    '20250223_remove_checkin_note.sql',
    '20251129154622_create_admin_global_config.sql',
    '20251219_drop_legacy_vella_settings_fields.sql',
    '20251220_fix_vella_settings.sql',
]

def compute_sha256(content):
    return hashlib.sha256(content.encode('utf-8')).hexdigest()

def escape_sql_string(s):
    return s.replace("'", "''").replace("\\", "\\\\")

migrations = []
for filename in expected_migrations:
    file_path = migrations_dir / filename
    content = file_path.read_text(encoding='utf-8')
    hash_value = compute_sha256(content)
    
    import re
    match = re.match(r'^(\d{8,14})_(.+)\.sql$', filename)
    if not match:
        raise ValueError(f"Invalid migration filename: {filename}")
    
    version = match.group(1)
    name = match.group(2)
    
    migrations.append({
        'version': version,
        'name': name,
        'filename': filename,
        'hash': hash_value,
        'statements': content
    })

sql = """-- ============================================================================
-- Supabase Migration Engine Rebuild Script
-- ============================================================================
-- This script completely rebuilds the migration engine tables.
-- Run this ONCE in the Supabase SQL Editor to normalize the migration system.
-- ============================================================================

BEGIN;

-- Drop old schema_migrations table if it exists
DROP TABLE IF EXISTS supabase_migrations.schema_migrations CASCADE;

-- Ensure schema exists
CREATE SCHEMA IF NOT EXISTS supabase_migrations;

-- Create migrations table with correct schema
CREATE TABLE IF NOT EXISTS supabase_migrations.migrations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version text NOT NULL,
    name text NOT NULL,
    hash text NOT NULL,
    executed_at timestamptz NOT NULL DEFAULT now(),
    statements text NOT NULL
);

-- Truncate existing data
TRUNCATE TABLE supabase_migrations.migrations;

-- Insert all migrations
"""

for migration in migrations:
    escaped_statements = escape_sql_string(migration['statements'])
    sql += f"""INSERT INTO supabase_migrations.migrations (version, name, hash, executed_at, statements)
VALUES ('{migration['version']}', '{migration['name']}', '{migration['hash']}', now(), '{escaped_statements}');

"""

sql += """COMMIT;

-- ============================================================================
-- Validation Query (run after commit to verify)
-- ============================================================================
-- SELECT version, name, hash, executed_at 
-- FROM supabase_migrations.migrations 
-- ORDER BY version;
"""

output_file.write_text(sql, encoding='utf-8')
print(f"✅ SQL file generated: {output_file}")

# Generate validation script
validation_script = f"""-- ============================================================================
-- Migration Validation Script
-- ============================================================================
-- Run this to verify all migrations are correctly inserted
-- ============================================================================

SELECT 
    version,
    name,
    hash,
    executed_at,
    LENGTH(statements) as statements_length
FROM supabase_migrations.migrations
ORDER BY version;

-- Expected count: {len(migrations)}
SELECT COUNT(*) as total_migrations FROM supabase_migrations.migrations;

-- Expected hashes:
"""
for migration in migrations:
    validation_script += f"-- {migration['version']}: {migration['hash']}\n"

validation_file = Path(__file__).parent.parent.parent / 'supabase' / 'validate_migrations.sql'
validation_file.write_text(validation_script, encoding='utf-8')
print(f"✅ Validation script generated: {validation_file}")

print("\n=== Migration Summary ===")
for migration in migrations:
    print(f"{migration['version']}: {migration['name']} (hash: {migration['hash'][:16]}...)")

print("\n✅ Rebuild script generation complete!")

